#!/usr/bin/env bun
// 一次性字体工具:从 Google Fonts 下载 Inter + JetBrains Mono 的 woff2(Google 已子集化,单字重 ~15-40KB),
// base64 内联进 ui/styles/fonts.css,实现自托管离线(保持单文件二进制零外部依赖)。
// 重新生成: bun run scripts/fetch-fonts.ts
// 注:中文走系统字体回退(App.tsx fontFamily 已配 PingFang/YaHei),不内联中文字体(体积过大)。
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&display=swap";

const css = await fetch(CSS_URL, { headers: { "User-Agent": UA } }).then((r) => r.text());
if (!css) throw new Error("empty css from google fonts (network blocked?)");

// 解析每个 @font-face:提取 family/weight/style/unicode-range/url
const faces: { family: string; weight: string; style: string; range?: string; url: string }[] = [];
const re = /@font-face\s*{([^}]*)}/g;
let m: RegExpExecArray | null;
while ((m = re.exec(css))) {
  const block = m[1];
  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const weight = /font-weight:\s*(\d+)/.exec(block)?.[1];
  const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? "normal";
  const range = /unicode-range:\s*([^;]+)/.exec(block)?.[1]?.trim();
  const url = /src:\s*url\(([^)]+)\)/.exec(block)?.[1];
  if (family && weight && url) faces.push({ family, weight, style, range, url });
}
console.log(`parsed ${faces.length} font faces (all unicode-ranges)`);
if (faces.length === 0) throw new Error("no faces parsed (UA may have returned ttf instead of woff2)");

// 只保留基本 latin range(U+0000-00FF):dashboard 只显示英文+数字,中文走系统字体回退(App.tsx 已配 PingFang/YaHei)。
// 去掉 cyrillic/greek/vietnamese/latin-ext,体积从 ~1.4MB 降到 ~0.4MB。
const keep = faces.filter((f) => f.range && f.range.includes("U+0000-00FF"));
console.log(`keep ${keep.length} basic-latin faces`);

// 下载每个 woff2 -> base64
const out: string[] = [
  "/* AUTO-GENERATED by scripts/fetch-fonts.ts. 自托管字体(Google woff2 子集 base64 内联),离线可用。",
  "   中文走系统字体回退(App.tsx fontFamily 配 PingFang/YaHei)。重新生成: bun run scripts/fetch-fonts.ts */",
];
let totalKb = 0;
for (const f of keep) {
  const buf = await fetch(f.url).then((r) => r.arrayBuffer());
  const b64 = Buffer.from(buf).toString("base64");
  totalKb += b64.length / 1024;
  const rangeLine = f.range ? `\n  unicode-range: ${f.range};` : "";
  out.push(
    `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;${rangeLine}
  src: url(data:font/woff2;base64,${b64}) format('woff2');
}`
  );
  console.log(`  ${f.family} ${f.weight} ${f.range ? "(" + f.range.slice(0, 24) + "…)" : ""}: ${(b64.length / 1024).toFixed(1)}KB`);
}

await Bun.write(import.meta.dir + "/../ui/styles/fonts.css", out.join("\n") + "\n");
console.log(`\nwrote ui/styles/fonts.css  (total base64: ${totalKb.toFixed(0)}KB)`);
